lib/takemefrom_web/router.ex
defmodule TakemefromWeb.Router do
  use TakemefromWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TakemefromWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TakemefromWeb.Plugs.SetCurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    # plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TakemefromWeb.Plugs.SetCurrentUser
  end

  scope "/", TakemefromWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/sessions", SessionController, only: [:new, :create, :delete], singleton: true
    resources "/registrations", RegistrationController, only: [:new, :create]
    resources "/play", PlayController, only: [:show]

    resources "/games", GameController, only: [:new, :edit, :index, :create, :delete] do
      get "/code", GameCodeController, :edit
      post "/code", GameCodeController, :update

      resources "/play", PlayV2Controller, only: [:show]
      resources "/observe", ObserveController, only: [:show]
    end

    get "/oauth2/github", Oauth2Controller, :github

    get "/oauth2/github/callback", Oauth2CallbacksController, :github
  end

  # Other scopes may use custom stacks.
  scope "/api", TakemefromWeb do
    pipe_through :api

    resources "/games", Api.GameController, only: [:show, :update]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: TakemefromWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/takemefrom_web/controllers/game_code_controller.ex
defmodule TakemefromWeb.GameCodeController do
  use TakemefromWeb, :controller

  alias Takemefrom.Games

  plug AuthenticateUser when action in [:edit, :update]

  def edit(conn, params) do
    game = Games.get_by!(slug: params["game_id"])

    content = game.elements |> Jason.encode!(pretty: true)

    render(conn, "edit.html", game: game, content: content)
  end

  def update(conn, params) do
    game = Games.get_by!(slug: params["game_id"])

    case params["game"]["elements"] |> Jason.decode() do
      {:ok, elements} ->
        Games.update_elements(game, elements)

        conn
        |> put_flash(:notice, "Your game has been created!")
        |> redirect(to: Routes.game_path(conn, :edit, game))

      {:error, _reason} ->
        conn
        |> put_flash(:error, "Invalid JSON provided")
        |> render("edit.html", game: game, content: params["game"]["elements"])
    end
  end
end

lib/takemefrom_web/views/game_code_view.ex
defmodule TakemefromWeb.GameCodeView do
  use TakemefromWeb, :view
end

lib/takemefrom_web/templates/game_code/edit.html.eex
<h1>Game Code Editor</h1>

<div class="content">

  <%= form_for @conn, Routes.game_game_code_path(@conn, :update, @game), [as: :game], fn f -> %>
    <div class="field">
      <%= label f, :elements %><br />
      <%= textarea f, :elements, value: @content %>
    </div>

    <div class="actions">
      <%= submit "Submit" %>
    </div>
  <% end %>
</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.0/codemirror.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/mode/javascript/javascript.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.0/codemirror.min.css" />

<script>
 var textarea = document.getElementById('game_elements')
 var editor = CodeMirror.fromTextArea(textarea, {
   lineNumbers: true,
   mode: "javascript"
 });
</script>