lib/takemefrom_web/router.ex
defmodule TakemefromWeb.Router do
  use TakemefromWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TakemefromWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TakemefromWeb.Plugs.SetCurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    # plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TakemefromWeb.Plugs.SetCurrentUser
  end

  scope "/", TakemefromWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/sessions", SessionController, only: [:new, :create, :delete], singleton: true
    resources "/registrations", RegistrationController, only: [:new, :create]
    resources "/play", PlayController, only: [:show]

    resources "/games", GameController, only: [:new, :edit, :index, :create, :delete] do
      get "/code", GameCodeController, :edit
      post "/code", GameCodeController, :update

      resources "/play", PlayV2Controller, only: [:show]
      resources "/observe", ObserveController, only: [:show]
    end

    get "/oauth2/github", Oauth2Controller, :github

    get "/oauth2/github/callback", Oauth2CallbacksController, :github
  end

  # Other scopes may use custom stacks.
  scope "/api", TakemefromWeb do
    pipe_through :api

    resources "/games", Api.GameController, only: [:show, :update]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: TakemefromWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/takemefrom_web/controllers/play_v2_controller.ex
defmodule TakemefromWeb.PlayV2Controller do
  use TakemefromWeb, :controller

  def show(conn, params) do
    token = Phoenix.Token.sign(conn, "player_salt", %{
      player_id: :rand.uniform(9999),
      game_slug: params["game_id"]
    })

    conn
    |> assign(:token, token)
    |> assign(:game_session_name, params["id"])
    |> assign(:game_slug, params["game_id"])
    |> render("show.html")
  end
end

lib/takemefrom_web/views/play_v2_view.ex
defmodule TakemefromWeb.PlayV2View do
  use TakemefromWeb, :view
end

lib/takemefrom_web/templates/play_v2/new.html.eex
<h1>Join the game</h1>

<div class="content">

  <%= form_for @conn, Routes.session_path(@conn, :show), [as: :player, method: "GET"], fn f -> %>
    <div class="field">
      <%= label f, :email %><br />
      <%= email_input f, :email %>
    </div>

    <div class="field">
      <%= label f, :password %><br />
      <%= password_input f, :password, autocomplete: "off" %>
    </div>

    <div class="actions">
      <%= submit "Log in" %>
    </div>
  <% end %>
</div>

<p class="choice"><%= link "Sign up", to: Routes.registration_path(@conn, :new) %></p>
<p class="choice"><%= link "Github", to: Routes.oauth2_path(@conn, :github) %></p>
<p class="choice light"><%= link "Go back", to: Routes.page_path(@conn, :index) %></p>

lib/takemefrom_web/templates/play_v2/show.html.eex
<div id="game-container"
     data-token=<%= @token %>
     data-game-session-name=<%= @game_session_name %>
     data-game-slug=<%= @game_slug %>
</div>